version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy to Staging Server
          command: |
            git push --force https://heroku:c3631a7f-fa25-43d5-9489-69e66286c978@git.heroku.com/webinar-demo-kat-staging.git master
  test:
    docker:
      - image: katalonstudio/katalon:latest
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio
          command: cd Tests && katalonc.sh -statusDelay=30 -retry=0 -projectPath="/root/project/Tests/test.prj" -testSuitePath="Test Suites/TS_RegressionTest" -executionProfile="staging" -browserType="Chrome (headless)" -apiKey=160cf81b-cbc7-43e7-9e57-7af7ee7943c9
  deploy:
    docker:
      - image: buildpack-deps:trusty
      
    steps:
      - checkout
      - run:
          name: Deploy to Production Server
          command: |
            git push --force https://heroku:c3631a7f-fa25-43d5-9489-69e66286c978@git.heroku.com/webinar-demo-kat-production.git master
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
