version: 2.1
orbs:
    katalonstudio: katalon/katalon-studio@23.0.8

workflows:
  build:
    jobs:
        - katalon-studio/run:
                version: "latest"
                katalon_param: '-browserType="Chrome" -retry=1 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"'
