version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force https://heroku:c3631a7f-fa25-43d5-9489-69e66286c978@git.heroku.com/webinar-demo-kat-staging.git master
  test:
    docker:
      - image: katalonstudio/katalon:7.2.1
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio
          command: cd Tests && katalon-execute.sh -statusDelay=30 -retry=0 -testSuitePath="Test Suites/TS_RegressionTest" -executionProfile="staging" -browserType="Chrome (headless)" 
      - store-test_results:
          path: ./report
      - store-artifacts:
          path: ./report
  deploy:
    docker:
      - image: buildpack-deps:trusty
      
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force https://heroku:c3631a7f-fa25-43d5-9489-69e66286c978@git.heroku.com/webinar-demo-kat-production.git master
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
